[package]
name = "mishkat-student"
version = "1.0.0"
description = "MISHKAT Student - Educational Desktop App for School Libraries"
authors = ["MISHKAT Team"]
edition = "2021"

[lib]
name = "mishkat_student_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
winreg = "0.52" # Used for writing to Windows registry for Proxy settings
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true
